---
- name: Secure Ubuntu Homeserver against DDoS and Intrusions
  hosts: all
  become: yes
  tasks:
  
    # Update and Upgrade APT packages
    - name: Ensure all packages are updated
      apt:
        update_cache: yes
        upgrade: 'safe'
      
    # Install some basic security tools
    - name: Install essential security packages
      apt:
        name:
          - fail2ban
          - ufw
          - unattended-upgrades
          - snort

    # Set up Fail2Ban to prevent brute-force login attempts
    - name: Ensure Fail2Ban is running and enabled on boot
      service:
        name: fail2ban
        state: started
        enabled: true
      
    # Configure and setup Snort as an IDS
    - name: Ensure Snort is running in IDS mode
      command: snort -A console -q -u snort -g snort -c /etc/snort/snort.conf -i wlp2s0
      become: yes
      become_method: sudo

