---
- name: Setup Pi-hole using Docker
  hosts: all
  vars_files:
    - ./variables/vars.yml
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    # Pull and run Pi-hole Docker container
    - name: Ensure Pi-hole directory exists
      file:
        path: /opt/pihole
        state: directory
        mode: '0755'

    - name: Deploy Pi-hole using Docker Compose
      docker_compose:
        project_name: pihole
        definition:
          version: '3'
          services: 
            pihole: 
              container_name: pihole
              image: pihole/pihole:latest
              ports: 
                - '53:53/tcp'
                - '53:53/udp'
                - '80:80/tcp'
                - '443:443/tcp'
              environment:
                TZ: 'Australia/Melbourne'
                serverIP: '192.168.1.106'
                WEBPASSWORD: '{{ pihole_web_password }}'
              volumes:
                - '/opt/pihole/etc-pihole/:/etc/pihole/'
                - '/opt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
              restart: unless-stopped
      

